### ISSUE TITLE
ReferenceError: "Promise" ist undefiniert

### ISSUE THREAD

**Issue by schefbi** [erz-mba-fbi/kursausschreibung#3]
With the following test in Internet Explorer you will encounter an error.

1. go to *subscribe form*.
2. go to *back with the form button*.
3. go to *subscribe form*.

`Error while processing route: list.category.event.subscribe "Promise" ist undefiniert ReferenceError: "Promise" ist undefiniert
   at e.getDropDownItems (https://localhost/assets/kursausschreibung.js:33:1628)
   at Anonymous function (https://localhost/assets/kursausschreibung.js:141:178)
   at Anonymous function (https://localhost/assets/kursausschreibung.js:141:79)
   at model (https://localhost/assets/kursausschreibung.js:141:1)
   at deserialize (https://localhost/assets/vendor.js:2555:109)
   at Anonymous function (https://localhost/assets/vendor.js:3287:6)
   at e.prototype.runSharedModelHook (https://localhost/assets/vendor.js:3286:1)
   at n.prototype.getModel (https://localhost/assets/vendor.js:3307:1)
   at _ (https://localhost/assets/vendor.js:3414:5)
   at P `

**Comment by schefbi** [comment]
Works
